name: CreatorAssist
version: '${project.version}'
main: com.kinoko2k.creatorassist.Creatorassist
api-version: 1.18
authors: [ Kinoko_2K ]
description: ver 1.18.1
website: kinoko2k.github.io

commands:
  ga:
    permission: creator.admin
    description: ゲームモードをアドベンチャーモードに切り替えます
    permission-message: あなたはゲームモードを切り替える権限がありません
    usage: /ga
  gc:
    permission: creator.admin
    description: ゲームモードをクリエイティブに切り替えます
    permission-message: あなたはゲームモードを切り替える権限がありません
    usage: /gc
  gs:
    permission: creator.admin
    description: ゲームモードをサバイバルモードに切り替えます
    permission-message: あなたはゲームモードを切り替える権限がありません
    usage: /gs
  gsp:
    permission: creator.admin
    description: ゲームモードをスペクテイターモードに切り替えます
    permission-message: あなたはゲームモードを切り替える権限がありません
    usage: /gsp
  br:
    permission: creator.admin
    description: バリアブロックを64個自分に付与します。
    permission-message: あなたはバリアブロックを付与する権限がありません
    usage: /br
  hideme:
    permission: creator.admin
    description: ゲームモードをinvisibleモードに切り替えます
    permission-message: あなたはinvisibleモードを切り替える権限がありません
    usage: /hideme

permissions:
  creator.player:
    description: ふつうのひと。
    default: true
  creator.admin:
    description: すべてを操れる。
    default: op